# Refitting and updating parameters

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.svm import SVC
X, y = load_iris(return_X_y=True)

In [4]:
clf = SVC()
clf.set_params(kernel='linear').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [5]:
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

In [6]:
clf.set_params(kernel='rbf', gamma='scale').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [7]:
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

# Multiclass vs. Multilabel fitting

In [9]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

In [10]:
X = [[1,2],[2,4],[4,5],[3,2],[3,1]]
y=[0,0,1,1,2]

In [11]:
classif = OneVsRestClassifier(estimator = SVC(gamma='scale', random_state=0))

In [12]:
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

In [13]:
Z = [[3,1],[4,5]]

In [14]:
classif.fit(X, y).predict(Z)

array([2, 1])

In [15]:
U = [[3,3],[8,8]]

In [20]:
classif.fit(X, y).predict(U)

array([0, 1])

In [22]:
U=[[111,9],[5,5]]

In [25]:
classif.fit(X, y).predict(U)

array([0, 1])

In [26]:
y = LabelBinarizer().fit_transform(y)

In [27]:
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
X


[[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]

In [31]:
from sklearn.preprocessing import MultiLabelBinarizer
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])